Camera trigger world
gazebosim/gz-sim pull request #1384
Opened 2022-03-10 22:34 UTC by WilliamLewww

# 🎉 Camera trigger world

Depends on:
* https://github.com/ignitionrobotics/ign-sensors/pull/194
* https://github.com/ignitionrobotics/sdformat/pull/846

## Summary
Created a camera trigger world to be used with the *ros_ign* example.

## Checklist
- [ ] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2022-03-11 09:35 UTC, ahcorde requested changes
examples/worlds/triggered_camera_sensor.sdf

2022-03-11 09:35 UTC, ahcorde commented on examples/worlds/triggered_camera_sensor.sdf
> +-->
Can you add here some command to trigger the camera using `ign` ?

2022-03-11 09:35 UTC, ahcorde commented on test/worlds/triggered_camera_sensor.sdf
> +<?xml version="1.0" ?>
is this file used in any tests ?

2022-03-11 18:20 UTC, WilliamLewww commented
Put into draft to make an integration test.

2022-04-28 21:19 UTC, WilliamLewww commented
Test failures irrelevant to pull request.
```
Ubuntu CI / Ubuntu Jammy CI (pull_request):
   The following tests FAILED:
  	 55 - UNIT_Gui_TEST (SEGFAULT)

ignition_gazebo-ci-pr_any-homebrew-amd64:
   The following tests FAILED:
	 29 - UNIT_SimulationRunner_TEST (SEGFAULT)
	239 - testFixture_TEST.py (Failed)
```

2022-05-04 08:41 UTC, ahcorde approved these changes

2022-05-06 21:15 UTC, merged