Updating hydrodynamics plugin description
gazebosim/gz-sim pull request #1502
Opened 2022-05-19 19:26 UTC by quarkytale

## Summary
Improved the hydrodynamics plugin parameters description to easily map with Fossen's book notation and understand their significance for usage.

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2022-05-19 19:27 UTC, quarkytale commented
Not sure if the checklist is applicable here and how to update the documentation

2022-05-19 23:45 UTC, chapulina approved these changes

2022-05-19 23:46 UTC, chapulina requested changes

2022-05-19 23:46 UTC, chapulina commented on src/systems/hydrodynamics/Hydrodynamics.hh
> +  /// The exact description of these parameters can be found on p. 37 and p. 43 of
Oh, linters are unhappy

```
  /github/workspace/src/systems/hydrodynamics/Hydrodynamics.hh:44:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
```

2022-05-20 01:07 UTC, arjo129 reviewed
LGTM. Just fix the linter errors highlighted by @chapulina

2022-05-23 20:19 UTC, chapulina approved these changes

2022-05-23 20:19 UTC, merged