Bash completion for flags
gazebosim/gz-sim pull request #1504
Opened 2022-05-21 03:11 UTC by mabelzhang

# 🎉 New feature

Part of https://github.com/gazebosim/gz-tools/issues/1
Used together with https://github.com/gazebosim/gz-tools/pull/87

## Summary

Bash completion, installation, tests.

## Test it

```
$ . install/share/gz/gz.completion
$ ign gazebo -
--force-version         --physics-engine        --verbose
--gui-config            --playback              --version
--help                  --record                --versions
--iterations            --record-path           -g
--levels                --record-resources      -h
--log-compress          --record-topic          -r
--log-overwrite         --render-engine         -s
--network-role          --render-engine-gui     -v
--network-secondaries   --render-engine-server  -z
```

## Checklist
- [x] Signed all commits for DCO
- [x] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2022-05-24 12:15 UTC, ahcorde requested changes

2022-05-24 12:15 UTC, ahcorde commented on src/cmd/gazebo.bash_completion.sh
> +#!/usr/bin/env bash
LICENSE

2022-05-24 12:15 UTC, ahcorde commented on src/cmd/gazebo.bash_completion.sh
> +    # Specify options (-*) word list for this subcommand
Add a TODO to include `--headless-rendering` from Fortress

2022-05-24 12:15 UTC, ahcorde commented on src/ign_TEST.cc
> +    "/src/cmd/gazebo.bash_completion.sh");
`ignition::common::jointPaths`

2022-06-03 07:41 UTC, ahcorde requested changes
CI is failing to compile
```
     std::string scriptPath = common::joinPaths(std::string(PROJECT_SOURCE_PATH),
```

2022-06-03 22:17 UTC, mabelzhang commented
Oops my Docker image was broken yesterday and I couldn't test things locally. Relying on CI

2022-06-04 03:24 UTC, mabelzhang commented
[b34bbe9](https://github.com/gazebosim/gz-sim/pull/1504/commits/b34bbe9ed7246c77706c10773427acd397d4c920) adds bash completion for the `model` command and tests it in a new way as described in https://github.com/gazebosim/gz-gui/pull/392#discussion_r889390294

2022-06-07 14:52 UTC, ahcorde commented on src/cmd/CMakeLists.txt
> +
```suggestion
```

2022-06-14 23:59 UTC, chapulina approved these changes
Pushed some minor tweaks in 7c0f3b9bcffce2a7b9b3feca7eb897c1d6ff0011. LGTM!

2022-06-15 17:59 UTC, merged