Utilizes function to load animations
gazebosim/gz-sim pull request #1568
Opened 2022-06-30 18:27 UTC by onurtore

Utilizes new LoadAnimations function to load animations trajectories during actor creation.

Part of three PR for the https://github.com/gazebosim/gz-sim/issues/1564#issue-1290407501 for slimming down the CreateActor function.

2022-06-30 18:28 UTC, onurtore commented
@ahcorde, 
Sorry for the old version, this must be a better.

2022-06-30 18:41 UTC, ahcorde requested changes

2022-06-30 18:41 UTC, ahcorde commented on src/rendering/SceneManager.cc
> +
```suggestion
```

2022-06-30 18:41 UTC, ahcorde commented on src/rendering/SceneManager.cc
> +    gzdbg << "AnimFilename " << animFilename << std::endl;
```suggestion
    gzdbg << "Loading actor [" << actor.Name() << " ] animation filename [" << animFilename << "]" << std::endl;
```

2022-06-30 18:41 UTC, ahcorde commented on src/rendering/SceneManager.cc
> +    gzdbg << "AnimScale " << animScale << std::endl;
```suggestion
    gzdbg << "Actor [" << actor.Name() << " ] animimation scale [" << animScale << "]" << std::endl;
```

2022-06-30 18:41 UTC, ahcorde commented on src/rendering/SceneManager.cc
> +    gzdbg << "Extension " << extension << std::endl;
is this debug trace required?

2022-06-30 18:41 UTC, ahcorde commented on src/rendering/SceneManager.cc
> +                << "]" << std::endl;
```suggestion
        gzerr << "Failed to get animations from [" << animFilename
              << "]" << std::endl;
```

2022-06-30 18:41 UTC, ahcorde commented on src/rendering/SceneManager.cc
> +      gzdbg << "Number of animations node " << meshSkel->AnimationCount() << std::endl;
remove ?

2022-06-30 18:41 UTC, ahcorde commented on src/rendering/SceneManager.cc
> +        gzdbg << "Adding Animation" << std::endl;
```suggestion
        gzdbg << "\t Adding Animation" << std::endl;
```

2022-06-30 18:41 UTC, ahcorde commented on src/rendering/SceneManager.cc
> +      gzdbg << "Adding animation is done" << std::endl;
```suggestion
      gzdbg << "Animation was added << std::endl;
```

2022-06-30 18:45 UTC, ahcorde requested changes
linters are also failing 

```
   /github/workspace/src/rendering/SceneManager.cc:2311:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
  /github/workspace/src/rendering/SceneManager.cc:2312:  Line ends in whitespace.  Consider deleting these extra spaces.  [whitespace/end_of_line] [4]
  /github/workspace/src/rendering/SceneManager.cc:2315:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
  /github/workspace/src/rendering/SceneManager.cc:2346:  Should have a space between // and comment  [whitespace/comments] [4]
  /github/workspace/src/rendering/SceneManager.cc:2352:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
  /github/workspace/src/rendering/SceneManager.cc:2352:  Should have a space between // and comment  [whitespace/comments] [4]
```

2022-06-30 18:58 UTC, onurtore commented on src/rendering/SceneManager.cc
> +    gzdbg << "Extension " << extension << std::endl;
No, none of these should be here.

2022-06-30 18:59 UTC, onurtore commented on src/rendering/SceneManager.cc
> +        gzdbg << "Node Count " << meshSkel->NodeCount() <<std::endl;
No, none of these should be here.

2022-06-30 19:37 UTC, ahcorde requested changes

2022-06-30 19:37 UTC, ahcorde commented on src/rendering/SceneManager.cc
> +                    extension.begin(), ::tolower);
```suggestion
                   extension.begin(), ::tolower);
```

2022-06-30 19:37 UTC, ahcorde commented on src/rendering/SceneManager.cc
> +              << std::endl;
```suggestion
          ignwarn << "File [" << animFilename
                  << "] has more than one animation, but only the 1st one is used."
                  << std::endl;
```

2022-06-30 19:37 UTC, ahcorde commented on src/rendering/SceneManager.cc
> +                << "]" << std::endl;
```suggestion
        ignerr << "Failed to get animations from [" << animFilename
               << "]" << std::endl;
```

2022-06-30 19:52 UTC, ahcorde requested changes
```
   /github/workspace/include/ignition/gazebo/rendering/SceneManager.hh:206:  Line ends in whitespace.  Consider deleting these extra spaces.  [whitespace/end_of_line] [4]
  /github/workspace/include/ignition/gazebo/rendering/SceneManager.hh:206:  Add #include <unordered_map> for unordered_map<>  [build/include_what_you_use] [4]
  /github/workspace/src/rendering/SceneManager.cc:2284:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
```

2022-06-30 20:26 UTC, ahcorde requested changes
https://github.com/gazebosim/gz-sim/runs/7138943766?check_suite_focus=true

2022-06-30 21:15 UTC, ahcorde requested changes
it's not compiling, see the comment

https://github.com/gazebosim/gz-sim/runs/7139388778?check_suite_focus=true

2022-06-30 21:15 UTC, ahcorde commented on src/rendering/SceneManager.cc
> +        return nullptr;
I'm not really sure if this should return `{}` or `mapAnimNameId`

2022-07-01 20:22 UTC, ahcorde requested changes
there are some conflicts too

2022-07-02 10:58 UTC, onurtore commented
> there are some conflicts too

Fixed the compilation error, did not see any other problems in the Build. Am i missing somewhere?

2022-07-04 05:36 UTC, ahcorde requested changes
There are some conflicts with `ign-gazebo6` too

2022-07-04 05:36 UTC, ahcorde commented on include/ignition/gazebo/rendering/SceneManager.hh
> +#include <unordered_map>
alphabetize headers

2022-07-04 05:36 UTC, ahcorde commented on src/rendering/SceneManager.cc
> +
```suggestion
```

2022-07-04 14:28 UTC, onurtore commented on src/rendering/SceneManager.cc
> +
Done.

2022-07-04 16:07 UTC, ahcorde approved these changes

2022-07-04 16:07 UTC, merged