Add Tf publishing to AckermannSteering system
gazebosim/gz-sim pull request #1576
Opened 2022-07-05 23:27 UTC by andyblarblar

🦟 Bug fix

Fixes #1573 

## Summary
Previously, the AckermannSteering system plugin did not publish tf alongside odometry, unlike the DiffDrive controller. This ment that when used with ROS, no odom->base_footprint was generated, preventing its use with SlamToolbox. This PR ports that DiffDrive tf publishing to the AckermannSteering controller, as well as the appropriate docs.

### Here's ackermann in use with slam-toolbox post fix:

![Peek 2022-07-05 19-19](https://user-images.githubusercontent.com/22401925/177432570-f4c7bad6-85f8-4bff-9636-19399ff6c72b.gif)

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [x] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2022-07-06 09:52 UTC, ahcorde requested changes

2022-07-06 09:52 UTC, ahcorde commented on src/systems/ackermann_steering/AckermannSteering.cc
> +  this->dataPtr->tfPub = this->dataPtr->node.Advertise<msgs::Pose_V>(
```suggestion
  auto tfTopic = validTopic(tfTopic);
  if (tfTopic.empty())
  {
    ignerr << "AckermannSteering plugin invalid tf topic name "
           << "Failed to initialize." << std::endl;
    return;
  }

  this->dataPtr->tfPub = this->dataPtr->node.Advertise<msgs::Pose_V>(
```

2022-07-06 09:52 UTC, ahcorde commented on src/systems/ackermann_steering/AckermannSteering.hh
> +  ///  and the default value is `/model/{name_of_model}/tf`.
```suggestion
  /// and the default value is `/model/{name_of_model}/tf`.
```

2022-07-06 09:52 UTC, ahcorde commented on src/systems/ackermann_steering/AckermannSteering.hh
> +  ///  and the default value is `{name_of_model}/{name_of_link}`.
```suggestion
  /// and the default value is `{name_of_model}/{name_of_link}`.
```

2022-07-06 09:52 UTC, ahcorde requested changes
Linters are failing https://github.com/gazebosim/gz-sim/runs/7208392386?check_suite_focus=true

2022-07-08 05:35 UTC, andyblarblar commented
I've implemented the suggestions and delt with the linter and CI. The fix is still fully working so it should be all set.

2022-07-08 07:53 UTC, ahcorde requested changes
can you add a test to check that the tf topic is generating data ?

2022-07-08 22:39 UTC, andyblarblar commented
Test added and passed.

2022-07-11 07:42 UTC, ahcorde requested changes

2022-07-11 07:42 UTC, ahcorde commented on test/integration/ackermann_steering_system.cc
> +      "/test/worlds/ackermann_steering_slow_odom.sdf"));
```suggestion
  serverConfig.SetSdfFile(common::joinPaths(std::string(PROJECT_SOURCE_PATH),
      "test", "worlds", "ackermann_steering_slow_odom.sdf"));
```

2022-07-18 15:08 UTC, ahcorde submitted a review, later dismissed
Uhm, focal is not happy https://github.com/gazebosim/gz-sim/runs/7385398190?check_suite_focus=true

2022-07-18 23:58 UTC, andyblarblar commented
The test failing on CI also fails on ign-gazebo6 for me, and contains no refrence to the files changed in this PR, so it seems to be a seprerate issue.

2022-07-22 23:55 UTC, chapulina approved these changes
LGTM, thanks!

2022-07-23 02:11 UTC, merged