Clarify errors when plugins fail to load
gazebosim/gz-sim pull request #1727
Opened 2022-09-21 20:13 UTC by mjcarroll

# 🦟 Bug fix

## Summary

I find that it's hard to tell one plugin failure mode from another with the current error messages.  This expands the messages and also includes relevant information for helping to diagnose system plugin issues.

## Checklist
- [ ] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2022-09-21 20:29 UTC, ahcorde requested changes
linters

2022-09-21 20:59 UTC, JoanAguilar approved these changes
I don't think I can't say much of the unit tests, the rest looks good to me (besides a minor comment).

2022-09-21 20:59 UTC, JoanAguilar commented on src/SystemLoader.cc
> +        ss << "  - " << pluginIt;
```suggestion
        ss << "  - " << pluginIt << "\n";
```

2022-09-21 21:15 UTC, mjcarroll commented
> I don't think I can't say much of the unit tests, the rest looks good to me (besides a minor comment).

I updated the tests to actually check the output for the general failure modes.

2022-10-12 18:46 UTC, ahcorde requested changes

2022-10-12 18:46 UTC, ahcorde commented on src/SystemLoader_TEST.cc
> +#include "gtest/gtest.h"
remove?

2022-10-12 18:46 UTC, ahcorde commented on src/SystemLoader.cc
> +      std::stringstream ss;
```cpp
#include <sstream>
```

2022-10-14 13:15 UTC, merged