Disable pybind11 on Windows by default
gazebosim/gz-sim pull request #2005
Opened 2023-06-06 17:06 UTC by Crola1702

# 🦟 Bug fix

(Copied from https://github.com/gazebosim/gz-math/pull/529)

Fixes part of #2003 (discussion on https://github.com/gazebosim/gz-launch/issues/220)

## Summary
This PR disabled pybind11 on windows by default until we fix the Windows build regressions that are related to #2003

## Checklist
- [ ] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2023-06-06 17:36 UTC, azeey commented on CMakeLists.txt
> +option(SKIP_PYBIND11
I think we'll need to use this variable as a condition where the pybind11 target is created. See https://github.com/gazebosim/gz-math/pull/528

2023-06-06 19:40 UTC, azeey requested changes
We're still doing `find_package(pybind11)` on line 206. That should be conditioned on `SKIP_PYBIND11`.

2023-06-06 19:40 UTC, azeey commented on CMakeLists.txt
> +      ${skip_pybind11_default_value})
Not sure if this setting should depend on `skip_pybind11_default_value`. Maybe it should depend on `SKIP_PYBIND11`, but I'm not even sure  of that. Maybe best to leave it unchanged.

2023-06-06 19:40 UTC, azeey commented on CMakeLists.txt
> +      ${skip_pybind11_default_value})
Same here. Probably should leave this unchanged.

2023-06-07 19:36 UTC, azeey approved these changes

2023-06-07 21:05 UTC, Crola1702 commented
I see `-- SKIP_PYBIND11 set - disabling python bindings` in https://build.osrfoundation.org/job/ign_gazebo-pr-win/5728/. So in theory, it's working fine.

2023-06-07 22:16 UTC, azeey commented
Looks like `mac-four` is having a permissions issue:

```
==> Reinstalling 4 dependents with broken linkage from source:
osrf/simulation/ignition-fuel-tools7, osrf/simulation/ignition-gui6, osrf/simulation/ignition-sensors6, osrf/simulation/ignition-transport11
Error: Could not rename ignition-fuel-tools7 keg! Check/fix its permissions:
  sudo chown -R $(whoami) /usr/local/Cellar/ignition-fuel-tools7/7.2.2
Build step 'Execute shell' marked build as failure
```

2023-06-08 14:28 UTC, j-rivero reviewed
Mostly fine, some minor comments.

2023-06-08 14:28 UTC, j-rivero commented on CMakeLists.txt
> +      message (STATUS "Searching for pybind11 - found version ${pybind11_VERSION}.")
NitPick: weird tabulation in this line and following coming probably from before but a good chance to fix that.

2023-06-08 14:28 UTC, j-rivero commented on CMakeLists.txt
> +if (MSVC)
We can probably comment here that we are disabling them by default because we don't have active CI on them but they could potentially work.

2023-06-08 14:28 UTC, j-rivero commented on CMakeLists.txt
> +if (pybind11_FOUND AND NOT SKIP_PYBIND11)
For `pybind11_FOUND` to be true it needs that `NOT SKIP_PYBIND11` would be also true given that the `find_package` command [is conditioned to it](https://github.com/gazebosim/gz-sim/pull/2005/files#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aR209-R213).  Does this work if we leave the code just:
```suggestion
if (pybind11_FOUND)
```

2023-06-12 15:48 UTC, j-rivero approved these changes

2023-06-12 21:10 UTC, merged