Adds bindings for the world convenience class
gazebosim/gz-sim pull request #2035
Opened 2023-07-18 13:16 UTC by Voldivh

# 🎉 New feature

## Summary
This PR creates the python bindings for the `World` convenience class.

## Checklist
- [ ] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2023-07-19 21:08 UTC, ahcorde requested changes

2023-07-19 21:08 UTC, ahcorde commented on python/src/gz/sim/World.cc
> +      "has a components::World.")
```suggestion
      "Check whether this world correctly refers to an entity that "
      "has a components::World.")
```

2023-07-19 21:08 UTC, ahcorde commented on python/src/gz/sim/World.cc
> +      "this world.")
```suggestion
      "Get the ID of a light entity which is an immediate child of "
      "this world.")
```

2023-07-19 21:08 UTC, ahcorde commented on python/src/gz/sim/World.cc
> +      "this world.")
```suggestion
      "Get the ID of a actor entity which is an immediate child of "
      "this world.")
  .def("model_by_name", &gz::sim::World::ModelByName,
      py::arg("ecm"),
      py::arg("name"),
      "Get the ID of a model entity which is an immediate child of "
      "this world.")
```

2023-07-19 21:08 UTC, ahcorde commented on python/src/gz/sim/World.cc
> +      "world.");
```suggestion
  .def("light_count", &gz::sim::World::LightCount,
      py::arg("ecm"),
      "Get the number of lights which are immediate children of this "
      "world.")
  .def("actor_count", &gz::sim::World::ActorCount,
      py::arg("ecm"),
      "Get the number of actors which are immediate children of this "
      "world.")
  .def("model_count", &gz::sim::World::ModelCount,
      py::arg("ecm"),
      "Get the number of models which are immediate children of this "
      "world.");
```

2023-07-19 21:08 UTC, ahcorde commented on python/test/world_TEST.py
> +        # This assertion should be `self.assertEqual(SphericalCoordinates(), self.world.spherical_coordinates(self.ecm))`
`> 100`

2023-07-25 23:59 UTC, Voldivh commented on python/src/gz/sim/World.cc
> +      "world.");
Done.

2023-07-25 23:59 UTC, Voldivh commented on python/src/gz/sim/World.cc
> +      "this world.")
Done.

2023-07-25 23:59 UTC, Voldivh commented on python/src/gz/sim/World.cc
> +      "this world.")
Done.

2023-07-25 23:59 UTC, Voldivh commented on python/src/gz/sim/World.cc
> +      "has a components::World.")
Done.

2023-08-08 15:31 UTC, Voldivh commented on python/test/world_TEST.py
> +from gz.sim8 import TestFixture, World, world_entity
Done.

2023-08-08 15:31 UTC, Voldivh commented on python/src/gz/sim/World.cc
> +namespace py = pybind11;
Done.

2023-08-08 15:31 UTC, Voldivh commented on CMakeLists.txt
> +#--------------------------------------
Done.

2023-08-08 19:23 UTC, azeey approved these changes
LGTM! The only remaining changes are to update sdformat13 to sdformat14

2023-08-08 19:23 UTC, azeey commented on .github/ci/packages.apt
> +python3-sdformat13
Update to sdformat14

2023-08-08 19:31 UTC, Voldivh commented on .github/ci/packages.apt
> +python3-sdformat13
Nice catch. Done.

2023-08-08 21:54 UTC, merged