Backport sensors system threading optimization changes
gazebosim/gz-sim pull request #2058
Opened 2023-07-27 21:57 UTC by iche033

# 🎉 New feature

## Summary
Backport changes from #1938 and #2025

## Test it

* Run the `INTEGRATION_sensors_system_update_rate` test
* Run the `sensors_demo.sdf` world to make sure sensors are working properly

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2023-07-28 01:56 UTC, mjcarroll approved these changes

2023-07-28 06:49 UTC, ahcorde requested changes

2023-07-28 06:49 UTC, ahcorde commented on src/systems/sensors/Sensors.cc
> -#include <map>
```
#include <atomic>
#include <chrono>
```

2023-07-28 06:49 UTC, ahcorde commented on test/integration/sensors_system_update_rate.cc
> +    "/test/worlds/sensor.sdf";
`gz::common::joinPath`

2023-07-28 12:39 UTC, mjcarroll commented on test/integration/sensors_system_update_rate.cc
> +    "/test/worlds/sensor.sdf";
good catch

2023-07-28 18:34 UTC, iche033 commented on test/integration/sensors_system_update_rate.cc
> +    "/test/worlds/sensor.sdf";
updated. [1d762d9](https://github.com/gazebosim/gz-sim/pull/2058/commits/1d762d90da3185ffe36e01bda7e10759026705dc)

2023-07-28 18:34 UTC, iche033 commented on src/systems/sensors/Sensors.cc
> -#include <map>
added. [1d762d9](https://github.com/gazebosim/gz-sim/pull/2058/commits/1d762d90da3185ffe36e01bda7e10759026705dc)

2023-07-31 06:57 UTC, ahcorde approved these changes

2023-07-31 06:57 UTC, merged