Revert to use of cos^2 in LiftDrag plugin
gazebosim/gz-sim pull request #2273
Opened 2023-12-27 02:04 UTC by arjo129

# 🦟 Bug fix

Fixes #<NUMBER>

## Summary
In response to https://github.com/gazebosim/gz-sim/pull/2189#issuecomment-1869798904

As suggested by @srmainwaring I also renamed cosSweepAngle ->
cos2SweepAngle to prevent further confusion.

## Checklist
- [ ] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2023-12-27 15:15 UTC, bperseghetti commented
Looks like it needs a rebase and a commit squash to the 3 lines changed from cos->cos2.

2023-12-28 00:03 UTC, arjo129 commented
> Looks like it needs a rebase and a commit squash to the 3 lines changed from cos->cos2.

It's OK theres no need to do anything since we squash and rebase before we merge into main in anycase.

2023-12-30 16:08 UTC, srmainwaring commented on src/systems/lift_drag/LiftDrag.cc
>    // get cos from trig identity
```suggestion
  // sweep adjustment depends on the velocity component which appears quadratically, so require cos^2.
```

2023-12-30 16:14 UTC, srmainwaring requested changes
LGTM. Suggested more detail in the comment to explain origin of formula.

2024-01-02 11:59 UTC, srmainwaring approved these changes

2024-01-02 18:47 UTC, azeey commented on src/systems/lift_drag/LiftDrag.cc
> +  // The sweep adjustment depends on the velocity component normal to the wing leading
linter seems unhappy about these lines.

2024-01-02 21:33 UTC, bperseghetti commented on src/systems/lift_drag/LiftDrag.cc
> +  double cos2SweepAngle = 1.0 - sinSweepAngle * sinSweepAngle;
No, shouldn't be an issue for the PX4 models.

2024-01-03 07:39 UTC, frede791 commented on src/systems/lift_drag/LiftDrag.cc
> +  double cos2SweepAngle = 1.0 - sinSweepAngle * sinSweepAngle;
No this is fine.

2024-01-08 13:13 UTC, bperseghetti approved these changes

2024-01-08 14:40 UTC, mjcarroll approved these changes

2024-01-08 14:40 UTC, merged