Parse and set bullet solver iterations
gazebosim/gz-sim pull request #2351
Opened 2024-04-01 20:35 UTC by iche033

# 🎉 New feature

## Summary

Added support for users to configure the bullet solver iterations. 

It parses the `//world/physics/bullet/solver/iters` SDF param and sets that value to the physics engine using the new Solver feature, `SetSolversIterations`, introduced in https://github.com/gazebosim/gz-physics/pull/609.  

## Checklist
- [ ] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2024-04-02 08:01 UTC, ahcorde requested changes

2024-04-02 08:01 UTC, ahcorde commented on src/LevelManager.cc
> +          uint32_t solverIterations = solverElem->Get<uint32_t>("iters");
include `<cstdint>`

2024-04-02 08:01 UTC, ahcorde commented on src/SdfEntityCreator.cc
> +          uint32_t solverIterations = solverElem->Get<uint32_t>("iters");
include `<cstdint>`

2024-04-02 18:30 UTC, iche033 commented on src/SdfEntityCreator.cc
> +          uint32_t solverIterations = solverElem->Get<uint32_t>("iters");
added. [35bce70](https://github.com/gazebosim/gz-sim/pull/2351/commits/35bce70ef3bf4df77f2b3e790f2c22e7ee43006c)

2024-04-02 18:30 UTC, iche033 commented on src/LevelManager.cc
> +          uint32_t solverIterations = solverElem->Get<uint32_t>("iters");
added. [35bce70](https://github.com/gazebosim/gz-sim/pull/2351/commits/35bce70ef3bf4df77f2b3e790f2c22e7ee43006c)

2024-04-02 18:31 UTC, iche033 commented on include/gz/sim/components/Physics.hh
> +  using PhysicsSolverIterations = Component<uint32_t,
added. [35bce70](https://github.com/gazebosim/gz-sim/pull/2351/commits/35bce70ef3bf4df77f2b3e790f2c22e7ee43006c)

2024-05-31 10:35 UTC, ahcorde approved these changes

2024-05-31 12:50 UTC, merged