Publish Joint forces
gazebosim/gz-sim pull request #2369
Opened 2024-04-12 09:45 UTC by Fixit-Davide

# 🦟 Bug fix

Fixes #883 

## Summary
These changes should allow to obtain information regarding the forces applied to the joints.

## Checklist
- [ ] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2024-04-12 10:21 UTC, ahcorde requested changes
do  you mind to sign the commit ?

2024-04-12 15:43 UTC, azeey commented
Also, can you please add a test?

2024-04-19 10:05 UTC, Fixit-Davide commented
I have just made a PR in gz-physics in order to populate the force fields while using bullet-featherstone. I added some information on how to test the code there (I have reported them here also).

2024-04-24 00:24 UTC, iche033 submitted a review, later dismissed
looks good to me

2024-04-24 00:26 UTC, iche033 reviewed
> Also, can you please add a test?

oh just saw that a test was requested.

2024-04-24 00:28 UTC, iche033 commented on src/systems/physics/Physics.cc
> +#include "gz/sim/components/JointForce.hh"
CI warning:
``` 
"gz/sim/components/JointForce.hh" already included at /github/workspace/src/systems/physics/Physics.cc:119  
```

2024-08-06 19:24 UTC, azeey commented
@Fixit-Davide  we are now in Feature freeze for Gazebo Ionic. Since PR is already open, I've applied the `beta` label which means it's slotted for the Ionic release if we can get it merged before 08/28/2024. Do you think that's feasible? If not, please let me know and I'll remove the `beta` label.

2024-08-12 19:21 UTC, azeey commented
To focus our efforts on the Ionic release, I'll go ahead and remove the `beta` label from this. I encourage you to respond to the feedback, but we'll hold off from merging this until Ionic is released.

2024-11-06 13:03 UTC, closed without merging