Fix #2458 - Checking linkEnity is empty
gazebosim/gz-sim pull request #2509
Opened 2024-08-04 09:33 UTC by akky20

# 🦟 Bug fix

Fixes #<NUMBER>

## Summary
Added a if condition for checking whether the linkEntity is empty or not , if this condition is removed then the issue comes again

## Checklist
- [ ] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2024-08-05 06:31 UTC, arjo129 requested changes
LGTM. This fixes the bug. However there is a minor style issue that needs fixing.

2024-08-05 14:01 UTC, akky20 reviewed
I have submitted the changes please have a look

2024-08-05 16:51 UTC, iche033 approved these changes

2024-08-06 00:26 UTC, arjo129 approved these changes

2024-08-06 00:26 UTC, merged