Physics: Ray intersections
gazebosim/gz-sim pull request #2514
Opened 2024-08-05 15:15 UTC by romulogcerqueira

# 🎉 New feature

Related to https://github.com/gazebosim/gz-sensors/issues/26 and https://github.com/gazebosim/gz-physics/pull/641

## Summary
This PR introduces components to hold rays and ray intersections data (`MultiRay` and `MultiRayIntersections`, respectively), and updates the physics system to compute the ray castings during `Update` loop.

## Test it
Added a test case to physics system.

Build and run `./build/bin/INTEGRATION_physics_system --gtest_filter=PhysicsSystemFixture.RayIntersections`

## Checklist
- [X] Signed all commits for DCO
- [X] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2024-08-06 03:09 UTC, azeey commented
Thanks for the PR! However, as stated in https://community.gazebosim.org/t/feature-freeze-for-gazebo-ionic/2900/2, we are now in feature freeze and will not review/merge any new PRs until after Ionic is released at the end of September. I hope you'll be able to iterate on the PR then.

2024-08-09 13:29 UTC, romulogcerqueira commented
> Thanks for the PR! However, as stated in https://community.gazebosim.org/t/feature-freeze-for-gazebo-ionic/2900/2, we are now in feature freeze and will not review/merge any new PRs until after Ionic is released at the end of September. I hope you'll be able to iterate on the PR then.

Thanks for the message, @azeey .

One question: Will all new features be redirected to Ionic, or will we maintain backward compatibility with Harmonic, since the latter is LTS?

2024-08-09 16:17 UTC, azeey commented
> One question: Will all new features be redirected to Ionic, or will we maintain backward compatibility with Harmonic, since the latter is LTS?

Once Ionic is released, we'll ask folks to target PRs to Ionic branches and the core team will backport to older release on a best-effort basis. Of course, you are welcome to backport it yourself. See https://community.gazebosim.org/t/gazebo-policy-update-new-backporting-policy/2880 for more details.

2024-12-22 18:13 UTC, ntfshard commented
It also can be useful for our use-cases I suppose. I guess this branch should be re-targeted on a last branch

2024-12-23 10:11 UTC, huqin-RM commented
@romulogcerqueira Will this feature be pushed forward to the official version?

2025-01-14 04:26 UTC, AliceCryer commented
I installed gazebosim with this repository to use this feature, however when attempting to use MultiRay in my plugin, colcon build cannot find the MultiRay.hh file. (I checked and the file is there, and VSCode has no issues with the import statement.) Do I need to adjust my CMakeLists.txt, or is there something specific I need to do to include the file? My code compiles fine otherwise

2025-01-15 18:45 UTC, romulogcerqueira commented
Hi @azeey,

With the release of Gazebo Ionic and the increasing interest from the Gazebo community in this feature (thanks @huqin-RM @ntfshard @AliceCryer), I’d like to move forward with this PR.

Could you please advise on the best way to proceed here, given that this PR targets `gz-sim8`?

2025-01-15 23:28 UTC, azeey commented
Per https://github.com/gazebosim/gz-sim/pull/2514#issuecomment-2278302526, could you target the `gz-sim9` branch? You could either use `git rebase` or `git reset --soft` to accomplish this. Once you push the changes, you'll then have to change the base branch on the Github interface. Let me know if you face any problems.

And thanks for your patience on this. It's on my queue to review, but I haven't had a chance yet.

2025-01-16 11:57 UTC, romulogcerqueira commented
> Per [#2514 (comment)](https://github.com/gazebosim/gz-sim/pull/2514#issuecomment-2278302526), could you target the `gz-sim9` branch? You could either use `git rebase` or `git reset --soft` to accomplish this. Once you push the changes, you'll then have to change the base branch on the Github interface. Let me know if you face any problems.
> 
> And thanks for your patience on this. It's on my queue to review, but I haven't had a chance yet.

Thanks! This PR is now targeting the `gz-sim9` branch and is ready for review again.

Since I'm using Harmonic, I'm also interested in the backport of this feature later.

2025-01-17 20:30 UTC, azeey requested changes
This is great work! Thanks again for the contribution. My main concern are:
- Naming of components
- Coordinate frames of quantities in components
- Usability: the need for two components

I would also ask you to add some documentation/tutorial that briefly shows how to use this and mentions that the Bullet collision engine must be used.

2025-01-17 20:30 UTC, azeey commented on src/systems/physics/Physics.cc
> +  // This means there are no systems that need contact information
```suggestion
  // This means there are no systems that need raycasting information
```

2025-01-17 20:30 UTC, azeey commented on src/systems/physics/Physics.cc
> +      this->entityWorldMap.EntityCast<RayIntersectionFeatureList>(worldEntity);
You should check if the cast was successful. If the feature isn't available in the physics engine, the pointer will be `nullptr`.

2025-01-17 20:30 UTC, azeey commented on include/gz/sim/components/MultiRay.hh
> +using MultiRay =
Does this essentially contain the requested rays to be cast? If so, can we change the name so that it's clear?

2025-01-17 20:30 UTC, azeey commented on include/gz/sim/components/MultiRay.hh
> +using MultiRayIntersections =
Looking at other raycasting APIs, the work "result" usually appears in the data structure used. The comment here also mentions result, so I'd recommend adding that to the name of the component.

2025-01-17 20:30 UTC, azeey commented on src/systems/physics/Physics.cc
> +            components::MultiRayIntersections>(
Does this mean the user has to create two components on the entity to use this feature? Would it be possible to combine them into one? Or we can have the physics engine be responsible for creating the result component (components::MultiRayIntersections).

2025-01-17 20:30 UTC, azeey commented on include/gz/sim/components/MultiRay.hh
> +  /// \brief Starting point of the ray in world coordinates
If this component is attached to an entity, it's natural to assume the start and end points would be expressed relative to that entity. If the user wants to use world coordinates, they would then just attach the component to the world entity.

2025-01-17 20:30 UTC, azeey commented on include/gz/sim/components/MultiRay.hh
> +  gz::math::Vector3d point;
Similar to my comment above, wouldn't make more sense to express these quantities relative to the frame of the entity this component is attached to?

2025-01-17 20:30 UTC, azeey commented on test/integration/physics_system.cc
> +          double exp_fraction =
nit: use `const`, use `camelCase` style

2025-01-23 14:48 UTC, romulogcerqueira commented on include/gz/sim/components/MultiRay.hh
> +struct RayIntersectionInfo
While [`dart::collision::RaycastResult`](https://github.com/dartsim/dart/blob/main/dart/collision/RaycastResult.hpp#L48) includes the collision object the ray hits, this information is currently not stored by `RayIntersection` in `gz-physics` (see [here](https://github.com/gazebosim/gz-physics/blob/gz-physics8/dartsim/src/SimulationFeatures.cc#L223) and [here](https://github.com/gazebosim/gz-physics/blob/gz-physics8/include/gz/physics/GetRayIntersection.hh#L36)).

We can open an issue to address this later. What do you think?

2025-01-23 15:11 UTC, romulogcerqueira commented on test/integration/physics_system.cc
> +          double exp_fraction =
Fixed in https://github.com/gazebosim/gz-sim/pull/2514/commits/34cbfd66e52c57028c8cc35cf19a917e6db41bb2

2025-01-23 15:11 UTC, romulogcerqueira commented on src/systems/physics/Physics.cc
> +      this->entityWorldMap.EntityCast<RayIntersectionFeatureList>(worldEntity);
Fixed in https://github.com/gazebosim/gz-sim/pull/2514/commits/34cbfd66e52c57028c8cc35cf19a917e6db41bb2

2025-01-30 09:57 UTC, ntfshard commented
Don't mind if I ask a question: lidar, based on this approach won't interact with particle system?
In other words, only solid geometry intersection and no smoke/noise/falling particles?
Just want to clarify limitations for myself C:

2025-01-30 17:53 UTC, iche033 commented
> Don't mind if I ask a question: lidar, based on this approach won't interact with particle system? In other words, only solid geometry intersection and no smoke/noise/falling particles? Just want to clarify limitations for myself C:

yes I believe that's correct. Particles are a visual only feature and currently do not have any geometries in the physics system.

2025-02-03 14:15 UTC, romulogcerqueira commented on src/systems/physics/Physics.cc
> +            components::MultiRayIntersections>(
Good suggestion!

I unified these two components in the `RaycastData` one. Done in https://github.com/gazebosim/gz-sim/pull/2514/commits/16791b71e8626cfec5e778677c7080c05b71866a

2025-02-03 14:16 UTC, romulogcerqueira commented on include/gz/sim/components/MultiRay.hh
> +  /// \brief Starting point of the ray in world coordinates
Agreed.

Done in https://github.com/gazebosim/gz-sim/pull/2514/commits/d4fe7807e20fb974331348fdb6da4d26521c1cbc

2025-02-03 14:16 UTC, romulogcerqueira commented on include/gz/sim/components/MultiRay.hh
> +using MultiRayIntersections =
Done in https://github.com/gazebosim/gz-sim/commit/16791b71e8626cfec5e778677c7080c05b71866a

2025-02-03 14:17 UTC, romulogcerqueira commented on include/gz/sim/components/MultiRay.hh
> +using MultiRay =
Unified  `MultiRay` and `MultiRayIntersections` components into `RaycastData` one in https://github.com/gazebosim/gz-sim/commit/16791b71e8626cfec5e778677c7080c05b71866a

2025-02-03 14:18 UTC, romulogcerqueira commented
@azeey, I've addressed all your suggestions.

Please let me know if you have any further feedback.

2025-02-04 00:02 UTC, azeey commented on include/gz/sim/components/MultiRay.hh
> +struct RayIntersectionInfo
Okay. Yes, let's open an issue then. I didn't realize it wasn't included in the gz-physics side.

Note that adding that capability will require an ABI break, hence a major version bump.

2025-02-04 00:25 UTC, azeey reviewed
This looks great to me! Just minor comments and one request for more documentation. Thanks again for or the contribution!

2025-02-04 00:25 UTC, azeey commented on include/gz/sim/components/RaycastData.hh
> +using RaycastData = Component<RaycastDataInfo, class RaycastDataTag>;
One of the problems we have in Gazebo is that the usage of Components is not easy to learn, especially when there's a sequence of operations that need to be performed, like the user adding the component and some other system updating the same component. Do you mind adding more detailed documentation here on how users are expected to use this component?

2025-02-04 00:25 UTC, azeey commented on src/systems/physics/Physics.cc
> +        results.clear();
Add `results.resize(rays.size())` to avoid memory allocations in the for loop?

2025-02-04 05:31 UTC, ntfshard commented on src/systems/physics/Physics.cc
> +        results.clear();
I guess you mean `reserve`, due to it will work fine with push_back

2025-02-04 13:04 UTC, romulogcerqueira commented on src/systems/physics/Physics.cc
> +        results.clear();
Good catch!

Done in https://github.com/gazebosim/gz-sim/pull/2514/commits/77802821ac38854e96542372371588a98b54dfe4

2025-02-04 16:35 UTC, azeey commented on src/systems/physics/Physics.cc
> +        results.clear();
> I guess you mean `reserve`, due to it will work fine with push_back

Yes, I did mean `reserve`. Thanks for the catch.

2025-02-04 16:48 UTC, azeey commented on include/gz/sim/components/RaycastData.hh
> +}
To avoid unnecessary serialization warnings, add the following
```c++
namespace serializers
{
  /// \brief Specialization of DefaultSerializer for RaycastDataInfo
  template<> class DefaultSerializer<components::RaycastDataInfo>
  {
    public: static std::ostream &Serialize(std::ostream &_out)
    {
      return _out;
    }

    public: static std::istream &Deserialize(std::istream &_in)
    {
      return _in;
    }
  };
}
```

We can customize this later if we do want to serialize the data for displaying the rays on the GUI.

2025-02-04 18:31 UTC, romulogcerqueira commented on include/gz/sim/components/RaycastData.hh
> +}
Done in https://github.com/gazebosim/gz-sim/pull/2514/commits/0787b62d18c45f9bbada36590d0d9fd3472fc7a4

2025-02-04 19:07 UTC, azeey approved these changes

2025-02-04 20:17 UTC, romulogcerqueira commented
Thanks for the review, @azeey.

Do you have any idea when this might be released?

I think this feature can be backported to Harmonic with minimal to no changes. Would it be okay if I open a new PR targeting `gz-sim8` once this one is merged?

2025-02-04 20:25 UTC, merged

2025-02-04 20:25 UTC, azeey commented
@Mergifyio backport gz-sim8