bugs in sdf_exporter.py
gazebosim/gz-sim pull request #2678
Opened 2024-11-16 18:06 UTC by mahit2609

Fix Blender SDF Export Tool for Blender 4.2.3
Overview
This PR fixes compatibility issues with Blender 4.2.3, as the original code was non-functional in newer Blender versions. The changes include API updates and bug fixes to ensure proper functionality.
Key Changes

Updated code to work with Blender 4.2.3's API
Fixed broken light handling and material processing
Updated type checks and property access to match current Blender standards

Notes

Tested working on Blender 4.2.3
Previous version was non-functional on newer Blender releases
Maintains same export format for model.dae, model.sdf, and model.config files

2024-12-16 18:00 UTC, azeey reviewed
Thanks for the contribution. Would you mind signing-off on your commits (see [contributing guide](https://gazebosim.org/docs/ionic/contributing/#process).

2024-12-16 18:00 UTC, azeey commented on examples/scripts/blender/sdf_exporter.py
> -# Tested Blender version: 2.82/3.2
Do you know if this updated script still works with 2.82/3.2?

2025-01-05 11:11 UTC, mahit2609 commented on examples/scripts/blender/sdf_exporter.py
> -# Tested Blender version: 2.82/3.2
no i am not sure i forgot to take it out while i was fixing the code for the 4 , but the code which is already there wont work even for 2.82

2025-01-06 21:35 UTC, azeey requested changes
Thanks again for the contribution! I started reviewing it, but I quickly realized there are a lot of unrelated changes (e.g. style, removed comments, etc.) that make it harder to review. Could you please revert those changes keeping only the relevant changes that fix the bugs so the PR is as small as possible?

2025-01-06 21:35 UTC, azeey commented on examples/scripts/blender/sdf_exporter.py
> +    bpy.ops.wm.collada_export(filepath=prefix_path+meshes_folder_prefix+dae_filename,
Can we keep the `path.join` here? That is preferred over using `+` for paths. And since there aren't any other changes, could you revert this to the previous version to reduce the diff as much as possible.

2025-01-06 21:35 UTC, azeey commented on examples/scripts/blender/sdf_exporter.py
> +
No need to remove the extra space. Please revert and minimize the diff.

2025-01-06 21:35 UTC, azeey commented on examples/scripts/blender/sdf_exporter.py
> -########################################################################################################################
Any reason for removing this comment?

2025-01-06 21:35 UTC, azeey commented on examples/scripts/blender/sdf_exporter.py
> +    mesh_objects = [o for o in objects if o.type == 'MESH']
Please revert unnecessary changes. This is only changing double quotes to single quotes. The rest of the file uses double quotes and I think it's best to stick with that.

2025-01-06 21:39 UTC, azeey commented on examples/scripts/blender/sdf_exporter.py
> -# Tested Blender version: 2.82/3.2
Okay. In that case, can you add a comment saying which version of Blender this is tested against?

2025-01-25 14:58 UTC, mahit2609 reviewed
i have made those changes and tested it on all the 4. versions of the blender can u please go through it i have kept it intact as much as i could thnx for the guidance

2025-01-27 17:19 UTC, azeey approved these changes
Thanks for the contribution. I only have one small comment.

2025-06-21 11:46 UTC, mahit2609 commented on examples/scripts/blender/sdf_exporter.py
> +        constant.text = "1.0"
Blender does not expose explicit linear/quadratic/constant attenuation values directly. Light falloff is defined via falloff type and radius, but not broken into explicit coefficients. Since we need these values explicitly for the export, they’re currently hardcoded.

2025-08-08 19:32 UTC, azeey approved these changes

2025-08-08 19:35 UTC, azeey commented
@mahit2609, can you please rebase on the latest `gz-sim9` branch and signoff all your commits. The DCO is still failing:
https://github.com/gazebosim/gz-sim/pull/2678/checks?check_run_id=37546491938

```
To add your Signed-off-by line to every commit in this branch:

Ensure you have a local copy of your branch by [checking out the pull request locally via command line](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally).
In your local branch, run: git rebase HEAD~3 --signoff
Force push your changes to overwrite the branch: git push --force-with-lease origin gz-sim9

Summary
Commit sha: [629adf6](https://github.com/gazebosim/gz-sim/pull/2678/commits/629adf67d0114b9e6d86dbf78adfaaf5af468c77), Author: mahit2609, Committer: mahit2609; The sign-off is missing.
```

2025-08-20 16:59 UTC, mahit2609 commented
@azeey the DCO is fixed now , Apologies for the delay. I was dealing with some personal/health issues and was very busy. Thank you for your patience!

2026-07-16 04:27 UTC, merged

2026-07-16 04:28 UTC, azeey commented
@mergifyio backport gz-sim10 gz-sim8 ign-gazebo6 main