Add parameter for adjust current sign for ROS
gazebosim/gz-sim pull request #2696
Opened 2024-12-10 01:32 UTC by Tacha-S

# 🦟 Bug fix

Fixes #2685 

## Summary

A parameter has been added to adjust the sign of the battery current value to comply with ROS conventions.
By default, it is set to `false`, so the existing behavior remains unchanged.

## Checklist
- [ ] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2024-12-10 08:38 UTC, ahcorde requested changes

2024-12-10 08:38 UTC, ahcorde commented on src/systems/battery_plugin/LinearBatteryPlugin.cc
> +  public: bool adjustCurrentSignForROS{false};
Do you mind to use a different value for the parameter ? We try not to include any ROS related stuff here.

Maybe something like `invertSignValues` ? But I open to suggestions

2024-12-10 08:54 UTC, ahcorde commented on src/systems/battery_plugin/LinearBatteryPlugin.cc
> +  public: bool adjustCurrentSignForROS{false};
go ahead with `invertCurrentSign` :ok_hand:

2024-12-13 20:22 UTC, azeey reviewed
Wouldn't this be easier to flip the sign only when the data is being published (PostUpdate) instead of adding extra logic at various places?

2024-12-17 00:17 UTC, Tacha-S commented
That's better. I’ve done it.

2024-12-17 01:02 UTC, azeey approved these changes
Thanks for the contribution!

2024-12-17 08:52 UTC, merged

2024-12-17 08:53 UTC, ahcorde commented
https://github.com/Mergifyio backport gz-sim8 ign-gazebo6